server:
  port: 8080
app:
  jwt:
    secret: mySecretCode
    tokenExpiration: 100m
    refreshTokenExpiration: 300m
spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/db_news
    username: postgres
    password: postgres
    hikari:
      schema: news_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS news_schema
      connection-timeout: 10000
  main:
    allow-circular-references: true
