version: '3'
services:
  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_news
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
volumes:
  db_data: