version: '3'

services:
  app-backend:
    image: news-channel:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/db_news
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_news
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: