version: '3'
services:
  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_news
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql